{% set version = "0.40.0" %}
{% set sha256 = "74f0e1494a0a9ca1327dcde5e1ac5483199abbe20a7702e0115d65014d0d32fe" %}

package:
  name: numba
  version: {{ version }}

source:
  url: https://github.com/numba/numba/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [win]
  entry_points:
    - pycc = numba.pycc:main
    - numba = numba.numba_entry:main
  script:
    - "{{ PYTHON }} buildscripts/remove_unwanted_files.py"
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  ignore_run_exports:
      # TBB is entirely optional
      - tbb

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - setuptools
    - llvmlite 0.25.*
    - numpy
    - tbb-devel >=2018.0.5
    - enum34          # [py2k]
    - singledispatch  # [py2k]
    - funcsigs        # [py2k]

  run:
    - python
    - {{ pin_compatible('llvmlite', max_pin='x.x') }}
    - {{ pin_compatible('numpy') }}
    - enum34          # [py2k]
    - singledispatch  # [py2k]
    - funcsigs        # [py2k]

  run_constrained:
    # If TBB is present it must be at least this version from Anaconda due to
    # build flag issues triggering UB in defaults::tbb=2018.0.4
    # See https://github.com/numba/numba/pull/3202#issuecomment-415939206 ff.
    - tbb >=2018.0.5

test:
  requires:
    - jinja2
    # Required to test optional Numba features
    - cffi
    - scipy
    - ipython
    - setuptools
    - tbb
    # Need these for AOT. Do not init msvc as it may not be present
    - {{ compiler('c') }}      # [not win]
    - {{ compiler('cxx') }}    # [not win]

  imports:
    - numba
    - numba.annotations
    - numba.cuda
    - numba.cuda.cudadrv
    - numba.cuda.kernels
    - numba.cuda.simulator
    - numba.cuda.simulator.cudadrv
    - numba.cuda.tests
    - numba.cuda.tests.cudadrv
    - numba.cuda.tests.cudadrv.data
    - numba.cuda.tests.cudapy
    - numba.cuda.tests.cudasim
    - numba.cuda.tests.nocuda
    - numba.datamodel
    - numba.jitclass
    - numba.npyufunc
    - numba.pycc
    - numba.rewrites
    - numba.runtime
    - numba.scripts
    - numba.servicelib
    - numba.targets
    - numba.testing
    - numba.tests
    - numba.tests.npyufunc
    - numba.typeconv
    - numba.types
    - numba.typing
    - numba.unsafe

about:
  home: http://numba.github.com
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: NumPy aware dynamic Python compiler using LLVM
  description: | 
    Numba is an Open Source NumPy-aware optimizing compiler for Python 
    sponsored by Anaconda, Inc. It uses the remarkable LLVM compiler 
    infrastructure to compile Python syntax to machine code."
  doc_url: http://numba.pydata.org/
  dev_url: https://github.com/numba/numba

extra:
  recipe-maintainers:
    - souravsingh
    - marcelotrevisani
