{% set name = "numba" %}
{% set version = "0.49.1" %}
{% set sha256 = "f430bb27c61379135be664dd1a105862d9656ac426ad343bb5c84dc2bcca4cc3" %}

package:
  name: numba
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/numba/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - pycc = numba.pycc:main
    - numba = numba.misc.numba_entry:main
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  ignore_run_exports:
    # TBB is entirely optional
    - tbb

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - setuptools
    - llvmlite 0.31.0
    - numpy
    - tbb-devel >=2019.5  # [linux]

  run:
    - python
    - llvmlite >=0.31.0,<0.33
    - {{ pin_compatible('numpy') }}
    # needed for pkg_resources
    - setuptools

  run_constrained:
    # If TBB is present it must be at least this version from Anaconda due to
    # build flag issues triggering UB in defaults::tbb=2018.0.4
    # See https://github.com/numba/numba/pull/3202#issuecomment-415939206 ff.
    - tbb >=2019.5  # [linux]

test:
  requires:
    # Required to test optional Numba features
    - jinja2
    - cffi
    - scipy
    - ipython
    - setuptools
    - tbb >=2018.0.5           # [linux]
    - intel-openmp             # [osx]
    # Need these for AOT. Do not init msvc as it may not be present
    - {{ compiler('c') }}      # [not win]
    - {{ compiler('cxx') }}    # [not win]

  imports:
    - numba
    - numba.annotations
    - numba.cuda
    - numba.cuda.cudadrv
    - numba.cuda.kernels
    - numba.cuda.simulator
    - numba.cuda.simulator.cudadrv
    - numba.cuda.tests
    - numba.cuda.tests.cudadrv
    - numba.cuda.tests.cudadrv.data
    - numba.cuda.tests.cudapy
    - numba.cuda.tests.cudasim
    - numba.cuda.tests.nocuda
    - numba.datamodel
    - numba.experimental.jitclass
    - numba.np.ufunc
    - numba.pycc
    - numba.rewrites
    - numba.runtime
    - numba.scripts
    - numba.roc.servicelib
    - numba.testing
    - numba.tests
    - numba.tests.npyufunc
    - numba.typeconv
    - numba.typing
    - numba.unsafe

about:
  home: http://numba.github.com
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: NumPy aware dynamic Python compiler using LLVM
  description: |
    Numba is an Open Source NumPy-aware optimizing compiler for Python 
    sponsored by Anaconda, Inc. It uses the remarkable LLVM compiler 
    infrastructure to compile Python syntax to machine code."
  doc_url: http://numba.pydata.org/
  dev_url: https://github.com/numba/numba

extra:
  recipe-maintainers:
    - souravsingh
    - marcelotrevisani
    - henryiii
    - mbargull
